apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-pred-app
  labels:
    app: churn-pred
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-pred
  template:
    metadata:
      labels:
        app: churn-pred
    spec:
      containers:
      - name: churn-pred-container
        # ECR Image
        image: 722998804831.dkr.ecr.us-east-1.amazonaws.com/churn_pred:latest 
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: app-secrets # Created by CI/CD pipeline
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: churn-pred-service
spec:
  type: LoadBalancer 
  selector:
    app: churn-pred
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
