artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_file_path: artifacts/data_ingestion/churn_data.csv
  raw_data_path: artifacts/data_ingestion/raw_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/churn_data.csv
  transformed_train_path: artifacts/data_transformation/train.csv
  transformed_test_path: artifacts/data_transformation/test.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.pkl
  metric_file_name: artifacts/model_evaluation/metrics.json
