name: CI/CD Pipeline

on: push

jobs:
  integration-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Latest method for caching

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run DVC Pipeline (Reproduce)
        env:
          PYTHONPATH: .
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          dvc repro

      - name: Run Model Validation Tests
        env:
          PYTHONPATH: .
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          python -m unittest tests/test_model.py

      - name: Promote Model to Production
        if: success()
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: python scripts/promote_model.py

      - name: Run API Integration Tests
        if: success()
        env:
          PYTHONPATH: .
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
        run: python -m unittest tests/test_fastapi.py

      # - name: Run Unit Tests
      #   run: python -m unittest discover tests

      # - name: Login to AWS ECR
      #   if: success()
      #   run: |
      #       aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #       aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #       aws configure set region ${{ secrets.AWS_REGION }}
      #       aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # - name: Build Docker Image
      #   if: success()
      #   run: |
      #       docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      # - name: Tag Docker Image
      #   if: success()
      #   run: |
      #       docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # - name: Push Docker Image to ECR
      #   if: success()
      #   run: |
      #       docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # - name: Set Up kubectl
      #   if: success()
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'latest'

      # - name: Update kubeconfig
      #   if: success()
      #   run: |
      #     aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name churn-pred-cluster

      # # Create Secret for App Env variables (from GitHub Secrets)
      # # Note: We group them into one generic secret 'app-secrets'
      # - name: Create Kubernetes Secret
      #   if: success()
      #   run: |
      #       kubectl create secret generic app-secrets \
      #       --from-literal=MONGO_DB_URL='${{ secrets.MONGO_DB_URL }}' \
      #       --from-literal=MLFLOW_TRACKING_URI='${{ secrets.MLFLOW_TRACKING_URI }}' \
      #       --from-literal=MLFLOW_TRACKING_USERNAME='${{ secrets.MLFLOW_TRACKING_USERNAME }}' \
      #       --from-literal=MLFLOW_TRACKING_PASSWORD='${{ secrets.MLFLOW_TRACKING_PASSWORD }}' \
      #       --from-literal=AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
      #       --from-literal=AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
      #       --from-literal=AWS_REGION='${{ secrets.AWS_REGION }}' \
      #       --dry-run=client -o yaml | kubectl apply -f -

      # - name: Deploy to EKS
      #   if: success()
      #   run: |
      #     kubectl apply -f deployment.yaml
